spring:
  profiles:
    active:
      dev:
        - dev
---
spring:
  profiles: dev # 开发环境
  application: 
    name: microservicecloud-config-scrh-dev

---
spring:
  profiles: test # 测试环境
  application: 
    name: microservicecloud-config-scrh-test
