spring:
  profiles:
    active:
      -dev

---
server:
  prot: 7001

spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的名称
  client:
    register-with-eureka: false # false表示不向服务注册中心注册自己
    fetch-registry: false # false表示自己就是注册中心，我的职责就是维护实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #设置与服务端Eureka Server交互的地址查询服务和注册服务都需要依赖于这个地址

---
server:
  prot: 7001

spring:
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的名称
  client:
    register-with-eureka: false # false表示不向服务注册中心注册自己
    fetch-registry: false # false表示自己就是注册中心，我的职责就是维护实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #设置与服务端Eureka Server交互的地址查询服务和注册服务都需要依赖于这个地址

